export const homepageText =  'Whether you`re looking to learn something new or offer your expertise, SkillSwap provides a seamless experience for everyone. Our community thrives on collaboration, ensuring that every interaction is meaningful and mutually beneficial. Join us today and take the first step towards expanding your knowledge, honing your talents, and meeting like-minded individuals.' ;
export const contentTitle = 'Meet new people and LEARN new skills for free!';
export const contentText = 'Discover a vibrant community eager to share experiences and knowledge.Our platform is designed to foster meaningful interactions. Dive into a world of endless possibilities where each connection brings new opportunities. Embrace the chance to grow your network and make lasting friendships. Start your journey today, and see how SwappSkills can help you meet new people and broaden your horizons. Join us and become part of a community where learning and sharing go hand in hand.';
export const contentTextStep1 = "Add all your new skills to your profile"
export const contentTextStep2 = "Search the topics you need to learn"
export const contentTextStep3 = "Build up your community by finding new people"
export const aboutUsPageText = "At Skill-Swap, we believe in the power of community learning and collaboration. Our platform, Skill-Swapp, connects individuals in our community to share and learn skills from one another. We strive to foster a culture of learning and growth, where everyone has something to teach and something to learn. We are dedicated to providing a safe and inclusive learning environment for all, and our team works hard to ensure that our platform is accessible to everyone. Whether you want to learn a new skill or teach one, Skill-Swapp is the perfect place to connect with others and grow together. "


